### ISSUE TITLE
Investigate flaky test problem

### ISSUE THREAD

**Issue by Quiddlee** [rolling-scopes/site#114]
# Evidence
![Image](https://github.com/rolling-scopes/site/assets/114234698/5a51c3b4-959c-4a43-9c8a-d9a0f82fe963)

![Image](https://github.com/rolling-scopes/site/assets/114234698/fccd38eb-b98c-4535-9553-fc483dc2be3c)

**Comment by Quiddlee** [comment]
Assignment removed because the bug could not be reproduced

**Comment by natanchik** [comment]
https://github.com/rolling-scopes/site/actions/runs/8965886122

**Comment by natanchik** [comment]
Proposed solution: refactor the component by removing the promise

![Image](https://github.com/rolling-scopes/site/assets/79564962/f0d7c54e-6b01-41b5-84f4-2065d5b9b291)

**Comment by Quiddlee** [comment]
The tests with this hook will be deleted in #602 hence issue will no longer exist
