### ISSUE TITLE
📝 Update And Refactor Website Routing

### ISSUE THREAD

**Issue by andron13** [rolling-scopes/site#167]
## 🎯 Describe the task:
The task involves a comprehensive check of the existing routing on our website. We'll then proceed to update it to a more modern style for efficiency and maintainability. As part of this process, we also aim to centralize all routes into a dedicated file, and refactor any components where these routes are used.

## ℹ️ Additional context:
Consolidating all routes into a single file improves scalability and simplifies future route management. It also brings clarity and ease of use to the project structure. This task should be carried out carefully to prevent potential disruptions to the existing functionality of the website.

## ✅ Definition of Done (DoD):
- All existing routes have been checked, updated, and migrated to a newer, more efficient style.
- A dedicated file for storing all routes has been created.
- All components using these routes have been refactored accordingly.
- The implementation does not disrupt the existing functionality nor introduce new bugs.
- The changes pass all existing tests.
- The task has been reviewed and approved by a peer.

**Comment by Quiddlee** [comment]
closed because of non relevant anymore
