### ISSUE TITLE
Courses first section different sizes

### ISSUE THREAD

**Issue by Quiddlee** [rolling-scopes/site#172]
## 🐛 Describe the Bug
The javascript (pre-school & js eng/ru) course component first section height is bigger the other courses

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to 'javascript course'
2. Navigate to 'other course except javascript'
3. see the difference

## 📸 Screenshots

![Image](https://github.com/rolling-scopes/site/assets/114234698/de588082-b51e-4dce-afb0-86b8382dda9d)
![Image](https://github.com/rolling-scopes/site/assets/114234698/7a47d8c3-724c-499e-b686-cbcbce6c141c)

## 🕹️ Device Information

- OS: Windows
- Browser: Chrome
- Version: latest

## ℹ️ Additional Context

N\A

## ✅ Definition of Done (DoD):

N\A

## 🕰️ Timeline:

N\A

**Comment by Manish9823** [comment]
Can you assign this task to me?

**Comment by andron13** [comment]
> Can you assign it to me?

Plz contact me in telegram @ptchom

**Comment by Tedzury** [comment]
@Quiddlee Is it acrually a bug? These titles just have a different content and it is the reason of diffing height, because JS courses have a subtitle in it, while other - does not.  Subtitle has exactly 28px height.🤷‍♂️ 

![Image](https://github.com/rolling-scopes/site/assets/101422512/44ffc501-090c-4867-a0cb-4f9f29e2c998)

**Comment by Quiddlee** [comment]
> @Quiddlee Is it actually a bug? These titles just have a different content and that is the reason of diffing height, because JS courses have a subtitle in it, while other - has not. Subtitle has exactly 28px height.🤷‍♂️
> 
> ![Image](https://private-user-images.githubusercontent.com/101422512/329148670-44ffc501-090c-4867-a0cb-4f9f29e2c998.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDUzNzMsIm5iZiI6MTcxNTI0NTA3MywicGF0aCI6Ii8xMDE0MjI1MTIvMzI5MTQ4NjcwLTQ0ZmZjNTAxLTA5MGMtNDg2Ny1hMGNiLTRmOWYyOWUyYzk5OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwODU3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmYzYjVlZDYxZGNjN2JiMWE0MzViNWIzYjEzNjVkNWVlMTQzOWNiMzQwOWVhMTU2Mzg1NGVmNjUyMzRlMDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C96qVNXe_SjhzXNbDQCLgZmrasUElPyyuMWbp4g6foE)

Let's discuss this tomorrow at the meeting
