### ISSUE TITLE
Stylelint issues

### ISSUE THREAD

**Issue by Quiddlee** [rolling-scopes/site#181]
## 🐛 Describe the Bug

Stylelint ain't fixes on stylelint:fix:
1. semicolons
2. space indents
3. empty spaces

## 📸 Screenshots
![Image](https://github.com/rolling-scopes/site/assets/114234698/f43c24b7-ac07-4a48-8403-3b84ca4fa9e3)

**Comment by ya6** [comment]
## StyleLint

- - The Errors and Warnings Section of StyleLint it says:

In addition to rule problems, Stylelint surfaces the following errors and warnings,
among which is "separate property and value pairs with colons"

it is prescribed there:

You should:
...
separate property and value pairs with colons
...

The source of information: https://stylelint.io/user-guide/errors/#unknown-word


## stylelint-prettier

- Attempt to use to solve this issue with "stylelint-prettier"

The source of information: https://github.com/prettier/stylelint-prettier

![Image](https://github.com/rolling-scopes/site/assets/52886210/d3a0213e-faaa-47e9-891f-fef0e0ed9b54)

After connecting and launching, the analysis of this error remained under 'postcss' control.

after launch npm run stylelint:fix

![Image](https://github.com/rolling-scopes/site/assets/52886210/5593e3a5-2128-4450-be16-9ca0390f2877)

## Conclusion:

- stylelint only provides an indication of this problem
-  stylelint reserves priority over stylelint-prettier
