### ISSUE TITLE
Pre school description typo

### ISSUE THREAD

**Issue by Quiddlee** [rolling-scopes/site#184]
## 🐛 Describe the Bug
typo in the pre school course description

## 📸 Screenshots

![Image](https://github.com/rolling-scopes/site/assets/114234698/b62956db-5be3-41cb-a65a-c8c5530db476)

**Comment by Tedzury** [comment]
@Quiddlee What exactly should be done? I don't see any typo in that phrase. I guess we should just remove this block from preschool layout, because this info is just incorrect. As I know, mentors are assigned only at frontend course, not at preschool.

**Comment by Quiddlee** [comment]
> @Quiddlee What exactly should be done? I don't see any typo in that phrase. I guess we should just remove this block from preschool layout, because this info is just incorrect. As I know, mentors are assigned only at frontend course, not at preschool.

That's correct
