### ISSUE TITLE
Delete course with expired date more than 3 weeks from upcoming courses

### ISSUE THREAD

**Issue by nchalovaa** [rolling-scopes/site#198]
## 🐛 Describe the Bug

Delete course with expired date more than 3 weeks from upcoming courses in the About Page

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to https://rs.school/community/#about
2. Scroll down to 'Upcoming courses'
3. Observe the error

## 🏁 Expected Behavior

There is no courses with expired date in on "Upcoming courses" section

## 📸 Screenshots

![Image](https://github.com/rolling-scopes/site/assets/149578850/3c8abaf0-578f-4f33-9f05-953d5196dbd8)

## 🕹️ Device Information

- Windows 10
- Browser: [Chrome]
- Version: [124]

**Comment by natanchik** [comment]
Related issue #61
