### ISSUE TITLE
Leave 1 variant of the description in the Readme

### ISSUE THREAD

**Issue by natanchik** [rolling-scopes/site#228]
## 🐛 Describe the Bug

There are 2 versions of `Introduction` (`Welcome to RS School`) and `Purposes` sections in the main Readme.
Select one description option at a time and delete the others from the main Readme.md file.

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to [repository](https://github.com/rolling-scopes/site/')
2. Scroll down to README
3. Observe the error

## 📸 Screenshots

![Image](https://github.com/rolling-scopes/site/assets/79564962/3383255b-1131-4ff6-8a05-a2077adb6975)
![Image](https://github.com/rolling-scopes/site/assets/79564962/5d3b3d82-c9e8-41c0-910c-b082e4b85add)

## ✅ Definition of Done (DoD):

- 1 section `Introduction` or `Welcome to RS School` without versions
- 1 section `Purpose` without versions

**Comment by andron13** [comment]
#230
