### ISSUE TITLE
Fix button education on the community page

### ISSUE THREAD

**Issue by nchalovaa** [rolling-scopes/site#263]
## 🐛 Describe the Bug

The button "Education" doesn't work. It is clickable, but doesn't contain any link or information.

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to https://pr258.rs.school/community/
2. Click on 'education" button
3. Observe the error

## 🏁 Expected Behavior

When user click on education button, there is a new tab with new information opened.

## 📸 Screenshots

![Image](https://github.com/rolling-scopes/site/assets/149578850/040766a6-d6ab-4680-9518-1a6740e82bc0)

## 🕹️ Device Information

- Windows 10
- Chrome, ver. 124

**Comment by ansivgit** [comment]
It was decided to remove this block from the page.
