### ISSUE TITLE
Fix unknown error when the browser window is small

### ISSUE THREAD

**Issue by nchalovaa** [rolling-scopes/site#264]
❗Before taking the issue, read this: https://github.com/rolling-scopes/site/pull/333/files#r1650181876

## 🐛 Describe the Bug

When the size of browser window is small there is an error in console

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to (https://rs.school/)
2. Change the size of browser window to the small one
3. Open the console
4. Observe the error

## 🏁 Expected Behavior

There is no error in console

## 📸 Screenshots

![Image](https://github.com/rolling-scopes/site/assets/149578850/ab15e14c-6d37-4340-a2c2-b8dfcd017800)

![Image](https://github.com/rolling-scopes/site/assets/149578850/79fe5aae-37de-4884-beb4-52587bc765ef)

## 🕹️ Device Information

Windows 10
Chrome, version 125

**Comment by ansivgit** [comment]
Blocked by #142

**Comment by ansivgit** [comment]
A solution was presented in PR https://github.com/rolling-scopes/site/pull/333, but it did not solve the issue - after clearing the cache, the error appeared again

**Comment by thirdmadman** [comment]
I contacted @nchalovaa and we found out that the error on the screenshot most likely comes from some kind of Google Chrome plugin or other tool in the browser because, in incognito mode, she could not reproduce the error.

**Comment by SpaNb4** [comment]
https://github.com/rolling-scopes/site/issues/264#issuecomment-2244566617
