### ISSUE TITLE
Lighthouse. SEO. Document does not have a meta description

### ISSUE THREAD

**Issue by ansivgit** [rolling-scopes/site#274]
## 📝 Describe the refactoring task

Document does not have a meta description

## 🛠️ Suggested improvement

[Link to Chrome documentation](https://developer.chrome.com/docs/lighthouse/seo/meta-description?utm_source=lighthouse&utm_medium=devtools&hl=ru)

## ℹ️ Additional context

![image](https://github.com/rolling-scopes/site/assets/56927722/51a35daf-8677-4830-bc62-d84dda90381a)
Issue #250 

## ✅ Definition of Done (DoD):

Fix this Lighthouse issue.

## 🕰️ Timeline:

Provide the deadline or estimated timeframe for the bug fix.

**Comment by MielomankA** [comment]
Depends on #250  PR #366

**Comment by SpaNb4** [comment]
Resolved by #366
