### ISSUE TITLE
Fix issues in layout in pages on mobiles

### ISSUE THREAD

**Issue by nchalovaa** [rolling-scopes/site#293]
## 🐛 Describe the Bug

There are some failures with layout **using the mobile**

## 🏁 Expected Behavior

There are no cropped headers or any text in mobile version.

## 📸 Screenshots

![Image](https://github.com/rolling-scopes/site/assets/149578850/b3c34f8b-16cc-4d6a-9190-28d06db6b2b6)

![Image](https://github.com/rolling-scopes/site/assets/149578850/95f0e12d-754f-4b0e-bbd5-928e1113abea)

## 🕹️ Device Information

Android Redmi Note 10 Pro
Chrome ver 125
Screen 6,67

**Comment by Yelunina** [comment]
Checked on 
Android emulator 14.0 x86_64,  iPhone 13 Pro max and DevTools. There are no cut off titles or text in the mobile version.
