### ISSUE TITLE
Fixing Display of Partner Icons in Course Section.

### ISSUE THREAD

**Issue by andron13** [rolling-scopes/site#313]
## 🐛 Describe the Bug

The task is about fixing the display of partner icons in the course section of the project.

![Image](https://github.com/rolling-scopes/site/assets/20660428/0c9f4a85-509e-4de6-b1ae-d4fb36f755a8)

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to 'https://rs.school/courses/reactjs)'
2. Scroll down to 'bottom.'
4. Observe the error

ℹ️ Additional context
Proper display of partner icons strengthens brand recognition for our associated partners and adds a layer of credibility to the course offerings.

✅ Definition of Done (DoD):
The task is considered done when the partner icons are displayed correctly across all screen sizes, devices, and browsers without any distortion or spacing issues.

**Comment by ansivgit** [comment]
I suppose, we need some design solution to accomplish this task

**Comment by thirdmadman** [comment]
In additional discussion with @IlliaSakharau we decided that icons in section "Partnered with" should be broken into grid with two columns after some breakpoint, similar to how it works in section "Our alumni".

We have been mentioning the breakpoint of 577px, but in current code, as I see in "Our alumni" the breakpoint is 810px.

**Comment by thirdmadman** [comment]
The same problem appears not only on course pages but on all pages with the component ```<Partnered />```.
