### ISSUE TITLE
Setting up ESLint for Feature-Sliced Design.

### ISSUE THREAD

**Issue by andron13** [rolling-scopes/site#320]
## 📝 Describe the feature

The task involves configuring ESLint for Feature-Sliced Design (FSD). Particularly, a rule needs to be set to restrict imports from unauthorized levels according to FSD rules & etc.

## ℹ️ Additional context

Feature-Sliced Design is a methodology for structuring front-end projects. Setting up ESLint rules according to FSD principles will enhance code quality by enforcing coding and structure standards.

## ✅ Definition of Done (DoD):

The task is considered finished when ESLint is set up in line with Feature-Sliced Design guidelines. Specifically, the import rule is successfully implemented, disallowing imports from unauthorized levels. All code should pass the new ESLint rules without any errors.

**Comment by Quiddlee** [comment]
Blocked by [#63](https://github.com/rolling-scopes/site/issues/63) untill we fully migrate to FSD and fix all the related errors
