### ISSUE TITLE
Lighthouse. Missing h1 element

### ISSUE THREAD

**Issue by Quiddlee** [rolling-scopes/site#371]
## 📝 Describe the refactoring task

Website is missing essential `h1` element on every course page.

## 🛠️ Suggested improvement

Add `h1` element on every page!

## ℹ️ Additional context

![Image](https://github.com/rolling-scopes/site/assets/114234698/6287456c-af81-4954-a965-e14e979af5d8)

**Comment by Wystov** [comment]
pr #350 changed div in title to h1, so after merging this issue will be resolved

**Comment by Quiddlee** [comment]
> pr #350 changed div in title to h1, so after merging this issue will be resolved

Every course page still missing `h1` element
