### ISSUE TITLE
Integration with RS APP to synchronize course data.

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/site#404]
I propose to automate course data update and get all current information from RS APP.
At the moment we have to manually create courses in RS APP, then create corresponding WeAreCommunity page, then update rs.school site and update it again when the course starts and WeAreCommunity page is archived. It's very boring :(

**Comment by natanchik** [comment]
To address the issue at hand, it's necessary to create a streamlined process that ensures timely updates and easy retrieval of courses information from RS APP.
- Setup Automated Sync: Implement a system that periodically fetches and updates the courses information from the specified URL (https://cdn.rs.school/app/courses.json). This can be done via a CRON job or a cloud function that runs at a set interval, ensuring that the data remains current.
- API Integration: Develop an API that can be used to fetch this courses information on demand. 
- Data Storage and Management: Once the data is retrieved, store it in a structured format within a database or a cloud storage solution that supports easy querying and data retrieval mechanics. This ensures that the data can be accessed quickly and efficiently.
