### ISSUE TITLE
Component refactoring

### ISSUE THREAD

**Issue by Quiddlee** [rolling-scopes/site#43]
**Goal:** Identify areas within the codebase that require refactoring for improved code organization, maintainability, and performance.

**Requirements:**

* Conduct a comprehensive analysis of the codebase to identify areas with potential for refactoring.
* Evaluate code structure, complexity, duplication, and adherence to design patterns.
* Determine the impact and feasibility of refactoring specific sections of the code.
* Prioritize refactoring opportunities based on their potential impact on maintainability, performance, and overall code health.
* Document the findings of the code analysis, including identified refactoring hotspots and recommendations for improvement.

**Deliverables:**

* A detailed report outlining the findings of the code analysis.
* List of prioritized refactoring opportunities along with their potential benefits and implementation considerations.
* Recommendations on appropriate refactoring strategies and techniques.

**Timeline:** Please estimate the time required to complete the analysis and provide the report.

**Notes:**

* Consult with the development team to understand the context and potential impact of refactoring certain areas. 
* Consider the overall project goals and limitations when prioritizing refactoring efforts.

**Contact:**

* For any questions or clarifications, please reach out to me @andron13.

**Comment by ansivgit** [comment]
It will be done in the FSD scope
