### ISSUE TITLE
Investigate: position of media queries in *.scss files

### ISSUE THREAD

**Issue by ansivgit** [rolling-scopes/site#434]
In DEV mode we have warnings in Terminal

![Image](https://github.com/user-attachments/assets/64fd0258-e99e-4b7c-ab4c-84881e8a0057)

We would like to investigate how we've change ESLint config to fix it automatically.

📍 Code location
*.scss files

🛠️ Suggested improvement
To change ESLint config

ℹ️ Additional context
At this point we suppose these warnings are related to the placement of directives @ at the top of the *.scss files, moving them below should fix this issues

Duplicate of #438 

✅ Definition of Done (DoD):
- find out how we have to change ESLint config (possibly in the stylelint plugins part);
- check if all other rules in *.scss files work correctly;
- no stylelint issues in Terminal

**Comment by thirdmadman** [comment]
To not lose this, I am attaching the config file of stylelint, in which rules, declarations, and at-rules are in fixed order according to the current code style.

This is not a decision or anything else.

``` lint-staged.config.mjs
// lint-staged.config.mjs
{
  "extends": ["stylelint-config-standard-scss", "stylelint-config-clean-order", "stylelint-prettier/recommended"],
  "plugins": [
    "stylelint-order"
  ],
  "rules": {
    "shorthand-property-no-redundant-values": null,

    "scss/load-no-partial-leading-underscore": null,
    "scss/double-slash-comment-empty-line-before": null,

    "scss/dollar-variable-empty-line-before": [
      "always",
      {
        "except": ["after-dollar-variable", "first-nested"],
        "ignore": ["after-comment", "inside-single-line-block"],
        "disableFix": true
      }
    ],

    "order/order": [
      "custom-properties",
      "dollar-variables",
      {
        "type": "at-rule",
        "name": "extend"
      },
      {
        "type": "at-rule",
        "name": "include"
      },
      {
        "type": "at-rule",
        "name": "include",
        "hasBlock": true
      },
      {
        "type": "at-rule",
        "hasBlock": true
      },
      {
        "type": "at-rule"
      },
      "declarations",
      "rules"
    ]
  }
}
```
