### ISSUE TITLE
Principle cards expand only on hover

### ISSUE THREAD

**Issue by Wystov** [rolling-scopes/site#439]
## 🐛 Describe the Bug

On main page cards explaining principles of the school expand only on hover, so no way to read their content on mobile devices.

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to '[main page](https://pr433.rs.school/#about)'
2. Hover on 'Open to everyone' card.
3. Repeat on mobile or set 'mobile' in devtools
4. Observe the error

## 🏁 Expected Behavior

Show all content in card if device doesnt support hover.

## 📸 Screenshots

![image](https://github.com/user-attachments/assets/f588c007-7ce4-4e83-8fb5-886a888c21ae)

**Comment by thirdmadman** [comment]
I guess there should be some design solution, and those cards could be represented differently on mobile devices.
Same as header menu behaves: on desktop, it uses mouse hover to reveal a submenu, but on mobile, it is hidden, and can be opened by clicking on burger menu button.

At this moment, I cannot actually find in figma files where this card came (wireframe, idea).
 I only see this as "result" in
https://www.figma.com/design/Yw1MzfCYDqDmJysNuQY8CO/Untitled?node-id=0-1&t=Ovt7OTagcd6ldtzt-0

We need design solution for this one.

**Comment by Illia-Sakharau** [comment]
### Approved design
Link to Figms: https://www.figma.com/design/5TzCcOInoZXkTA0TvL6cku/Untitled-(Copy)?node-id=2017-3&t=6UQRoYmTI3Ih2grS-1

![image](https://github.com/user-attachments/assets/46a4dd69-a6a1-4470-b90a-8b3000b2864c)
