### ISSUE TITLE
FSD: Event-card refactor

### ISSUE THREAD

**Issue by KristiBo** [rolling-scopes/site#440]
## 📝 Describe the refactoring task

Event-card component refactor

## 📍 Code location

`@/entities/events`

## ℹ️ Additional context

Related to #346 

## ✅ Definition of Done (DoD):

Event-card component has been refactored

**Comment by Quiddlee** [comment]
@KristiBo please check this issue - #472. There is a step by step guide

**Comment by KristiBo** [comment]
duplicate issue #472
