### ISSUE TITLE
FSD: Widget About

### ISSUE THREAD

**Issue by Quiddlee** [rolling-scopes/site#489]
## 📝 Describe the refactoring task

Part of the issue #347 
About component refactor

## 📍 Code location

`src/widgets/about/ui/about.tsx`

## ✅ Definition of Done (DoD):

1. rename `about` folder and component to `about-course`
2. Refactor `about-course.tsx` and `info-grid.tsx` `scss` to `scss modules` including:

-   remove all parent selector `& .card-content` -> `.card-content`. 
-   change all possible values to variables if such exists.
-   rename all classes to be generic e.g `.nodejs-trainer 🙅‍♂️` -> `.trainer 👌`.
-   and everything in your opinion that needs to be refactored

#### `info-grid.tsx`
1. remove all comments
2. change all the `interfaces` to `types`
3. refactor JSX to utilize HTML5 tags
4. remove `hasTitle` prop completely
5. get rid of `dangerouslySetInnerHTML` prop (just pass info as usual - between the tags)
6. replace `h2` with `WidgetTitle`

####  `about-course.tsx`
1. change all the `interfaces` to `types`
2. move `CourseNames` to `courses-data.types.ts`
3. move `about-course.tsx`, `about-course.module.scss` and `about-course.test.tsx` to `src/widgets/about-course/ui/about-course`

**Comment by ansivgit** [comment]
Blocked #375 because subheadings in `info-grid` should be the `Subtitle` component
