### ISSUE TITLE
Dedicated page for mentors

### ISSUE THREAD

**Issue by MikAleinik** [rolling-scopes/site#580]
## 📝 Describe the feature

Create a dedicated page for mentors where detailed information will be posted:
- who can be a mentor, how to be a mentor
- detailed description with links in RS App on how to register as a mentor
- how the mentoring process works, time commitment, mentor activities
- description of rewards to mentors for active participation in student learning
- block of videos about the mentoring process 

## ℹ️ Additional context

The page should consist of existing FSD components as much as possible.

#### Mentoring page
- [x] a separate page for mentors has been created
- [ ] (canceled) menu link in the header is page oriented on the created page
- [x] links on other pages in mentoring blocks are oriented on the created page
- [x] page contains information on who can be a mentor
- [x] page contains information on how to be a mentor
- [x] detailed description with links in RS App on how to register as a mentor
- [x] how the mentoring process works, time commitment, mentor activities
- [ ] description of rewards to mentors for active participation in student learning
- [ ] block of videos about the mentoring process
**Update 16.10.2024**
- [x] from the menu item “RSSchool” remove the item "Mentoring"
- [x] in the header change the color to #2BB4EF
- [x] in the header place links to the course under mentorship
- [x] in the “HeroPage” block, change the color to #73ccf2
- [x] in the “HeroPage” block for the general page, change the text to “RS Mentorship” + “Teach it forwards” + remove “since 2013”
- [ ] the “HeroPage” block for the general page should be different from the mentoring block for a particular course, using the “HeroPage” block for the selected course as a basis
- [x] in the “Mentorship details” block at a resolution of less than +- 600px course images should be hidden
- [x] do not show the “Mentorship is for you if you” block when a course is selected
- [ ] after the “Any questions” block, add the standard “Communication” block from the course pages
- [ ] after the “Mentorship detail” block for the general page, add a short block of cards with a transition to mentoring a specific course
#### Corrections
- [x] references to documentation must begin with https://docs.rs.school/#/en/
- [x] make the background of the “Any questions” block light
- [x] in the “HeroPage” block, adjust the image height
- [x] in the “Mentor details” block, correct the title text to “Mentor details”
- [ ] in the “Mentor activities” block, put a picture of a sloth
- [ ] in the “Mentorship details” block check why the edges of images are cropped
- [ ] in the block “Mentorship is for you if you” increase the font similar to “Course” -> “About the course”
- [x] in the “Mentorship is for you if you” block, add the ability to place icons
- [x] in the “Registration by mentor” block, increase the text indentation to 40px
- [x] in the “Any questions” block place icons under the text
- [x] check out all the problems shown Lighthouse
#### Second stage
- [ ] implement a block for mentors/students to write feedback
- [ ] implement a block course statistics, with information about the number of students in the course and the number of students without a mentor
- [ ] create e2e tests

#### Another resources
- [ ] update information in documentation https://docs.rs.school/#/rs-school-mentor
- [ ] to bring the information in the documentation in https://docs.app.rs.school/#/platform/pull-request-review-process accordance with the previous paragraph

## Additional link
Issue #395 with a general description.
Documentation for mentor https://docs.rs.school/#/rs-school-mentor
Documentation for mentor https://docs.app.rs.school/#/platform/pull-request-review-process
Link to mentor registry https://app.rs.school/registry/mentor

**Comment by Quiddlee** [comment]
@MikAleinik If you want, we can break up the task into smaller pieces, so other developers could help to implement this. Or even create a separate dedicated meeting with a group of people ready to help with this?

**Comment by MikAleinik** [comment]
Sorry for the long answer.
Right now it's hard for me to break down the task in more detail.
I want to make a draft version and after showing it to the team to clarify the requirements for the final solution.

**Comment by MikAleinik** [comment]
Added an update after mit 14.10
