### ISSUE TITLE
Upgrade the ESLint version from v8.x to v9.x

### ISSUE THREAD

**Issue by SpaNb4** [rolling-scopes/site#584]
## 📝 Describe the refactoring task
Upgrade the ESLint version from v8.x to v9.x. ESLint v8.x will reach end-of-life on 2024-10-05 and will not be maintained after that https://eslint.org/version-support/

## ✅ Definition of Done (DoD):
- ESLint version is upgraded to v9.x
- The eslint.config.js file is updated with any necessary configuration changes
- All existing linting rules continue to pass without any new errors or warnings

**Comment by Quiddlee** [comment]
@SpaNb4 [duplicated issue](https://github.com/rolling-scopes/site/issues/101)
