### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by andron13** [rolling-scopes/site#64]
❗ **Part of issue #45** 

**Goal:** Improve webpage performance and user experience by migrating to system fonts and investigate the benefits of asynchronous font loading.

**Requirements:**

* Research the advantages and potential challenges of using system fonts for web projects.
* Propose a font-selection strategy that leverages system fonts while ensuring consistent fallback mechanisms for compatibility.
* Implement the selected font strategy across the website or application.
* Investigate the feasibility and potential performance benefits of loading critical fonts asynchronously.
* Develop a solution for asynchronous font loading using appropriate techniques, such as `preload` or `@font-face` with the `font-display` property.
* Thoroughly test the implemented font solution across different browsers, devices, and network conditions.

**Deliverables:**

* Implementation of system fonts throughout the website or application.
* Proposed and documented font strategy.
* Solution for asynchronous font loading (if deemed appropriate).
* Comprehensive testing report on font rendering and performance.

**Timeline:** Please estimate the time required for each task and provide a delivery schedule.

**Notes:**

* Consider browser support, font availability, and potential impact on accessibility for different user groups.
* Evaluate potential licensing or usage restrictions associated with certain system fonts.
* Prioritize the asynchronous loading of essential fonts that contribute to initial page rendering.

**Contact:**

* For any questions or clarifications, feel free to contact me @andron13.

![image](https://github.com/rolling-scopes/site/assets/114234698/f9a253c4-ecd0-4d6b-8cc1-3cfcf594da31)

**Comment by Illia-Sakharau** [comment]
Partially completed within the scope of #493
