### ISSUE TITLE
Refactoring define-prev-next.ts functionality

### ISSUE THREAD

**Issue by Illia-Sakharau** [rolling-scopes/site#85]
**Goal:** Improve code readability and prevent bad code smell

**Path to the file:** src/app/hooks/use-nearest-course/utils/define-prev-next.ts

**Comment by andron13** [comment]
@Illia-Sakharau 
what does the task mean? i didn`t understand.

**Comment by Illia-Sakharau** [comment]
> @Illia-Sakharau what does the task mean? i didn`t understand.
@andron13 
I have written code that works, but for other developers it is difficult to read and violates the principle of single responsibility. I have to separate the logic and make the code more understandable to others.

**Comment by Wystov** [comment]
this file was deleted during refactoring. closing issue

**Comment by Wystov** [comment]
this file was deleted during refactoring. closing issue
